
CREATE TABLE Orders(
	Order_id	INTEGER NOT NULL,
	Customer_id	INTEGER NOT NULL UNIQUE,
	Total	NUMERIC(8,2),
	Status	VARCHAR(15),
	Order_date	TIMESTAMP(15) NOT NULL,
	fk1_Customer_id	INTEGER NOT NULL,
	UNIQUE(fk1_Customer_id),
	CONSTRAINT	pk_Order PRIMARY KEY (Order_id)
);

CREATE TABLE Order_details(
	Order_id	INTEGER NOT NULL,
	Position	INTEGER NOT NULL,
	Product_id	INTEGER NOT NULL,
	Quantity	INTEGER,
	Price	NUMERIC(8,2),
	fk1_Product_id	INTEGER NOT NULL,
	Order_idOrder_id	INTEGER NOT NULL,
	CONSTRAINT	pk_Order_details PRIMARY KEY (Order_id,Position)
);

CREATE TABLE Customer(
	Customer_id	INTEGER NOT NULL,
	First_name	VARCHAR(15) NOT NULL,
	Last_name	VARCHAR(20) NOT NULL,
	Street&no	VARCHAR(25) NOT NULL,
	City	VARCHAR(30) NOT NULL,
	ZIP	VARCHAR(8) NOT NULL,
	Region	VARCHAR(25),
	Country	VARCHAR(30) NOT NULL,
	PhoneNo	VARCHAR(12) NOT NULL,
	Email	VARCHAR(20),
	Cust_category	VARCHAR(15),
	fk1_Name	VARCHAR(15) NOT NULL,
	UNIQUE(fk1_Name),
	CONSTRAINT	pk_Customer PRIMARY KEY (Customer_id)
);

CREATE TABLE Product(
	Product_id	INTEGER NOT NULL,
	Title	VARCHAR(30) NOT NULL,
	Category	VARCHAR(15) NOT NULL,
	Plot_desc	VARCHAR(500),
	Prod_country	VARCHAR(20) NOT NULL,
	Prod_Year	VARCHAR(8) NOT NULL,
	Rating	VARCHAR(8),
	Format	VARCHAR(8),
	fk1_Name	VARCHAR(8) NOT NULL,
	UNIQUE(fk1_Name),
	fk2_Name	VARCHAR(8) NOT NULL,
	UNIQUE(fk2_Name),
	CONSTRAINT	pk_Product PRIMARY KEY (Product_id)
);

CREATE TABLE Cust_category(
	Name	VARCHAR(15) NOT NULL,
	Cust_Cat_desc	VARCHAR(50),
	CONSTRAINT	pk_Cust_category PRIMARY KEY (Name)
);

CREATE TABLE Category(
	Name	VARCHAR(8) NOT NULL,
	Cat_desc	VARCHAR(50),
	CONSTRAINT	pk_Category PRIMARY KEY (Name)
);

CREATE TABLE Rating(
	Name	VARCHAR(8) NOT NULL,
	Rating_desc	VARCHAR(200),
	CONSTRAINT	pk_Rating PRIMARY KEY (Name)
);


ALTER TABLE Product ADD CONSTRAINT fk1_Product_to_Rating FOREIGN KEY(fk1_Name) REFERENCES Rating(Name) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE Product ADD CONSTRAINT fk2_Product_to_Category FOREIGN KEY(fk2_Name) REFERENCES Category(Name) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE Order_details ADD CONSTRAINT fk1_Order_details_to_Product FOREIGN KEY(fk1_Product_id) REFERENCES Product(Product_id) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE Customer ADD CONSTRAINT fk1_Customer_to_Cust_category FOREIGN KEY(fk1_Name) REFERENCES Cust_category(Name) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE Order_details ADD CONSTRAINT fk2_Order_details_to_Order FOREIGN KEY(Order_idOrder_id) REFERENCES Order(Order_id) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE Orders ADD CONSTRAINT fk1_Order_to_Customer FOREIGN KEY(fk1_Customer_id) REFERENCES Customer(Customer_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

